approvedGitRepositories:
  - '**'

enableScripts: true

npmMinimalAgeGate: 0

nodeLinker: node-modules

packageExtensions:
  'rs-ui-base@*':
    peerDependencies:
      '@angular/common': '*'
      '@angular/core': '*'
      '@angular/material': '*'
      '@ngx-translate/core': '*'
      '@ngx-translate/http-loader': '*'
      'ngx-mask': '*'
      'rxjs': '*'
      'tslib': '*'
