approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmPreapprovedPackages:
  - '@LeeZX24/*'

npmScopes:
  LeeZX24:
    npmRegistryServer: "https://npm.pkg.github.com"
