approvedGitRepositories:
  - '**'

enableScripts: true

npmMinimalAgeGate: 0

nodeLinker: node-modules

npmScopes:
  LeeZX24:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAuthToken: "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"
